/**
 * REAL JOB PHOTOGRAPHY, per department.
 *
 * This is the manifest behind the "What done looks like" section on each
 * service page. It is the difference between the site showing stock imagery and
 * the site showing evidence — so the distinction is encoded, not assumed:
 *
 *   own: true   → Lunova's own completed work. Section is headed as such and
 *                 may claim the result.
 *   own: false  → reference/illustrative imagery. Section says so plainly.
 *
 * Never flip `own` to true for an image you did not shoot on a Lunova job. The
 * whole value of this section is that a customer can trust it, and a single
 * reverse-image hit on a stock photo destroys that for every other claim on the
 * page.
 *
 * FILE LOCATIONS — originals go in assets-src/work/<service-key>/ and are NOT
 * deployed. Run `pnpm images` to generate the responsive variants into
 * public/images/work/<service-key>/. The `file` field below is the base name,
 * with no directory, width suffix, or extension.
 */

import { hasWorkPhoto } from "./workManifest";

export interface WorkPhoto {
  /** Base filename, no extension. Variants are generated by `pnpm images`. */
  file: string;
  alt: string;
  /** Optional short caption shown under the photo. */
  caption?: string;
}

export interface BeforeAfterPair {
  before: string;
  after: string;
  beforeAlt: string;
  afterAlt: string;
}

export interface ServiceGallery {
  /** True only for photography shot on Lunova's own jobs. */
  own: boolean;
  heading: string;
  blurb: string;
  photos: WorkPhoto[];
  /** Optional drag-slider pair, for services where the change is the product. */
  beforeAfter?: BeforeAfterPair;
}

export const SERVICE_GALLERIES: Record<string, ServiceGallery> = {
  "power-washing": {
    own: true,
    heading: "What done looks like",
    blurb:
      "Same driveway, same day. Drag the slider to see moss and algae lifted off aggregate concrete without etching the surface.",
    photos: [],
    beforeAfter: {
      before: "driveway-before",
      after: "driveway-after",
      beforeAlt: "Concrete driveway covered in moss and algae growth before pressure washing",
      afterAlt: "The same concrete driveway cleaned to an even finish after pressure washing",
    },
  },

  landscaping: {
    own: true,
    heading: "What done looks like",
    blurb: "Recurring lawn care on a Lunova route: cut, edged, and cleaned up.",
    photos: [
      {
        file: "lawn-front-yard",
        alt: "A dense, evenly mown front lawn with a cleanly edged sidewalk line",
        caption: "Recurring lawn care, mown, edged, and blown clean",
      },
    ],
  },

  "auto-detailing": {
    own: true,
    heading: "What done looks like",
    blurb: "Paint correction, interior work, and engine bays, finished to hand-off standard.",
    photos: [
      {
        file: "sedan-exterior",
        alt: "A dark red sedan after a full exterior detail, paint reflecting cleanly with no swirl marks",
        caption: "Full exterior detail: decontaminated, polished, sealed",
      },
      {
        file: "engine-bay",
        alt: "A clean engine bay after an engine detail, with no residue on plastics or hoses",
        caption: "Engine bay detail: degreased and dressed",
      },
    ],
  },

  /**
   * Residential cleaning has no confirmed own-work photo yet.
   *
   * The interior shot supplied alongside the other photos looks like styled
   * interior-design photography rather than a Lunova job — so it is flagged
   * `own: false` and the copy stays honest. If it IS a real completed clean,
   * flip the flag and rewrite the blurb; if it is not, replace it.
   */
  "residential-cleaning": {
    own: false,
    heading: "The standard we work to",
    blurb:
      "Reference photography showing the finish we aim for. Our own job photos go up as we complete them.",
    photos: [
      {
        file: "bedroom-styled",
        alt: "A tidy, styled bedroom with made bed, clear surfaces and vacuumed floor",
      },
    ],
  },
};

/**
 * Resolves a department's gallery down to what actually exists on disk.
 *
 * Declarations above are aspirational — a photo can be named here before its
 * file has been dropped into assets-src/work/. This filters against the
 * generated manifest so a missing file hides its photo (and a before/after pair
 * missing either frame drops the whole slider) instead of shipping a broken
 * image. Returns undefined when nothing survives, and WorkGallery renders null.
 */
export function getGallery(serviceKey: string): ServiceGallery | undefined {
  const gallery = SERVICE_GALLERIES[serviceKey];
  if (!gallery) return undefined;

  const photos = gallery.photos.filter((p) => hasWorkPhoto(serviceKey, p.file));

  const pair = gallery.beforeAfter;
  const beforeAfter =
    pair && hasWorkPhoto(serviceKey, pair.before) && hasWorkPhoto(serviceKey, pair.after)
      ? pair
      : undefined;

  if (photos.length === 0 && !beforeAfter) return undefined;

  return { ...gallery, photos, beforeAfter };
}
